### ISSUE TITLE
Issue with Web app | Unsupported operation: Platform._localeName

### ISSUE THREAD

**Issue by AnhNgDo** [google-wallet/flutter-plugin#1] opened 2024-02-14 23:51 UTC
Good day,

I'm trying out Google Wallet to let users collect generic pass in Flutter's web app. However, it keeps throwing the following error (tested in Web Debug and Build mode): 

> ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
> The following UnsupportedError was thrown building GoogleWalletButton(dirty):
> Unsupported operation: Platform._localeName
> 
> The relevant error-causing widget was:
>   GoogleWalletButton

The error was from this call in _checkAvailable method in the example code: `available = await googleWallet.isAvailable();`

As a side note, tested on Android simulator and it seems to work.

Any help is much appreciated!

**Comment by linussorg** [comment] 2024-02-18 02:22
@AnhNgDo 
This is more or less intended behaviour, as far as I can tell. `Platform._localeName` is from `dart:io`, which does not exist on the web platform, therefore throwing an error. This library currently only supports Android (see https://pub.dev/packages/google_wallet). Maybe web support could be added, not sure whether or not it's possible / planned.

**Comment by stephenmcd** [comment] 2024-03-08 01:48
It would be very cool to support a web version, although off the top of my head I don't think it's feasible since there wouldn't be a way to sign the pass JWTs. I'll close this for now, but if someone can prove me wrong please re-open this and we can use it to track the feature request.

Thank you

**Closed as completed by stephenmcd** 2024-03-08 01:48 UTC
